import { createFileRoute, Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { HeartPulse, Stethoscope, FileText, Activity, ShieldCheck, Sparkles } from "lucide-react";

export const Route = createFileRoute("/")({
  component: Landing,
});

function Landing() {
  return (
    <div className="min-h-screen bg-background">
      {/* Nav */}
      <header className="border-b border-border bg-card/70 backdrop-blur sticky top-0 z-10">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <div className="size-9 rounded-lg gradient-primary flex items-center justify-center shadow-soft">
              <HeartPulse className="size-5 text-primary-foreground" />
            </div>
            <span className="font-semibold text-lg">MediSense</span>
          </Link>
          <div className="flex items-center gap-2">
            <Link to="/login"><Button variant="ghost">Sign in</Button></Link>
            <Link to="/register"><Button>Get started</Button></Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="gradient-soft">
        <div className="max-w-6xl mx-auto px-6 py-20 lg:py-28 grid lg:grid-cols-2 gap-12 items-center">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-accent text-accent-foreground text-xs font-medium mb-6">
              <Sparkles className="size-3.5" /> AI-powered health insights
            </div>
            <h1 className="text-4xl lg:text-6xl font-bold tracking-tight leading-tight">
              Understand your symptoms,{" "}
              <span className="bg-clip-text text-transparent gradient-primary">instantly</span>.
            </h1>
            <p className="mt-5 text-lg text-muted-foreground max-w-xl">
              Describe what you feel and receive structured insights: possible conditions,
              precautions, specialist suggestions, and health advice — generated by medical-grade AI.
            </p>
            <div className="mt-8 flex flex-wrap gap-3">
              <Link to="/register"><Button size="lg" className="gap-2">Start free check <Stethoscope className="size-4" /></Button></Link>
              <Link to="/login"><Button size="lg" variant="outline">I already have an account</Button></Link>
            </div>
            <p className="mt-6 text-xs text-muted-foreground max-w-md">
              Informational only. MediSense is not a substitute for professional medical advice,
              diagnosis, or treatment.
            </p>
          </div>

          <div className="relative">
            <div className="rounded-2xl bg-card border border-border shadow-elegant p-6 space-y-4">
              <div className="flex items-center gap-3">
                <div className="size-10 rounded-lg bg-accent flex items-center justify-center">
                  <Activity className="size-5 text-primary" />
                </div>
                <div>
                  <div className="text-sm font-semibold">Symptom analysis</div>
                  <div className="text-xs text-muted-foreground">Generated in ~3 seconds</div>
                </div>
              </div>
              <div className="space-y-2 text-sm">
                <div className="p-3 rounded-lg bg-muted">
                  <div className="text-xs text-muted-foreground">Possible condition</div>
                  <div className="font-medium">Seasonal allergic rhinitis · <span className="text-warning-foreground bg-warning/30 px-2 py-0.5 rounded text-xs">moderate</span></div>
                </div>
                <div className="p-3 rounded-lg bg-muted">
                  <div className="text-xs text-muted-foreground">Suggested specialist</div>
                  <div className="font-medium">ENT or Allergist</div>
                </div>
                <div className="p-3 rounded-lg bg-muted">
                  <div className="text-xs text-muted-foreground">Precaution</div>
                  <div className="font-medium">Stay hydrated · avoid known triggers</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="max-w-6xl mx-auto px-6 py-20 grid md:grid-cols-3 gap-6">
        {[
          { icon: Stethoscope, title: "AI Symptom Checker", desc: "Structured analysis from a powerful medical-aware LLM." },
          { icon: FileText, title: "Personal Health Reports", desc: "Every analysis is saved and searchable in your history." },
          { icon: ShieldCheck, title: "Private & Secure", desc: "Row-level encryption and access controls protect your data." },
        ].map(({ icon: Icon, title, desc }) => (
          <div key={title} className="rounded-xl bg-card border border-border p-6 shadow-card">
            <div className="size-10 rounded-lg gradient-primary flex items-center justify-center mb-4">
              <Icon className="size-5 text-primary-foreground" />
            </div>
            <h3 className="font-semibold mb-1">{title}</h3>
            <p className="text-sm text-muted-foreground">{desc}</p>
          </div>
        ))}
      </section>

      <footer className="border-t border-border bg-card">
        <div className="max-w-6xl mx-auto px-6 py-8 text-sm text-muted-foreground flex flex-wrap justify-between gap-3">
          <div>© {new Date().getFullYear()} MediSense — Smart Health Prediction System</div>
          <div>Informational use only. Not medical advice.</div>
        </div>
      </footer>
    </div>
  );
}
